- name: Enable RPM Fusion
  ansible.builtin.import_playbook: rpm_fusion.yaml

- name: Install Terminal packages
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Enable COPR repository for Starship
      ansible.builtin.command: dnf copr enable -y atim/starship
      become: yes

    - name: Install terminal utilities
      ansible.builtin.dnf:
        name:
          - git
          - fzf
          - zoxide
          - starship
          - podman
          - podman-compose
          - gh
        state: present
      become: yes

- name: Install General Packages
  hosts: localhost
  tasks:
    - name: Enable COPR repository for PrismLauncher
      ansible.builtin.command: dnf copr enable -y g3tchoo/prismlauncher
      become: yes

    - name: Install general packages
      ansible.builtin.dnf:
        name:
          - wireshark
          - torbrowser-launcher
          - steam
          - prismlauncher
          - https://mega.nz/linux/repo/Fedora_{{ ansible_distribution_version }}/x86_64/megasync-Fedora_{{ ansible_distribution_version }}.x86_64.rpm # MegaSync
          - https://zoom.us/client/latest/zoom_x86_64.rpm # Zoom
        state: present
      become: yes

- name: Install Signal
  ansible.builtin.import_playbook: signal.yaml

- name: Install VSCodium
  ansible.builtin.import_playbook: vscodium.yaml

- name: Install Virt Manager
  ansible.builtin.import_playbook: virt_manager.yaml

- name: Install TinyTeX
  ansible.builtin.import_playbook: tinytex.yaml