- name: Terminal
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Enable COPR repository for Starship
      ansible.builtin.command: dnf copr enable -y atim/starship
      become: yes

    - name: Install terminal utilities
      ansible.builtin.dnf:
        name:
          - git
          - fzf
          - zoxide
          - starship
        state: present
      become: yes
