- name: Install TinyTex
  hosts: localhost
  vars:
    tinytex_root: "{{ ansible_env.HOME }}/.local/share/TinyTeX"
    installer_path: /tmp/install-bin-unix.sh

  tasks:
    - name: Ensure TinyTeX directory exists
      file:
        path: "{{ tinytex_root }}"
        state: directory
        mode: '0755'

    - name: Download TinyTeX installer script
      get_url:
        url: https://yihui.org/tinytex/install-bin-unix.sh
        dest: "{{ installer_path }}"
        mode: '0755'

    - name: Run TinyTeX installer as the remote user
      become: yes
      become_user: "{{ ansible_user | default(ansible_env.USER) }}"
      environment:
        TINYTEX_ROOT: "{{ tinytex_root }}"
      command: /bin/sh -c "{{ installer_path }}"
      args:
        creates: "{{ tinytex_root }}/bin"
