- name: VSCodium
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create the VSCodium .repo file
      ansible.builtin.copy:
        dest: /etc/yum.repos.d/vscodium.repo
        content: |
          [gitlab.com_paulcarroty_vscodium_repo]
          name=gitlab.com_paulcarroty_vscodium_repo
          baseurl=https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/rpms/
          enabled=1
          gpgcheck=1
          repo_gpgcheck=1
          gpgkey=https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
          metadata_expire=1h
      become: yes

    - name: Install VSCodium
      ansible.builtin.dnf:
        name: codium
      become: yes

    - name: Install VSCodium extensions
      ansible.builtin.command:
        codium --install-extension {{ item }}
      loop:
        - james-yu.latex-workshop
        - ms-python.black-formatter
        - ms-python.debugpy
        - ms-python.python
