- name: Install Zoom Client
  hosts: localhost
  tasks:
    - name: Install Zoom package directly from URL
      ansible.builtin.apt:
        deb: "https://zoom.us/client/latest/zoom_amd64.deb"
        state: present
      become: yes