- name: Install Mega Client
  hosts: localhost
  tasks:
    - name: Read lsb-release file
      ansible.builtin.slurp:
        src: /etc/upstream-release/lsb-release
      register: lsb_release_content

    - name: Set DISTRIB_RELEASE fact
      set_fact:
        distrib_release: "{{ (lsb_release_content['content'] | b64decode).split('\n') | select('search', '^DISTRIB_RELEASE=') | first | regex_replace('^DISTRIB_RELEASE=', '') }}"

    # Mega runs a post install script that adds an old style list file for their repo, conflicting with the new style source, resulting in a corrupted apt config. Just let them do their thing.
    - name: Install Mega package directly from URL
      ansible.builtin.apt:
        deb: "https://mega.nz/linux/repo/xUbuntu_{{ distrib_release }}/amd64/megasync-xUbuntu_{{ distrib_release }}_amd64.deb"
        state: present
      become: yes