- name: Install Signal Messenger
  hosts: localhost
  tasks:
    - name: Add Signal repository
      ansible.builtin.deb822_repository:
        name: signal
        types: deb
        uris: https://updates.signal.org/desktop/apt
        suites: xenial
        components: 
          - main
        signed_by: https://updates.signal.org/desktop/apt/keys.asc
        architectures: 
          - amd64
        become: true

    - name: Install Signal
      ansible.builtin.apt:
        name: signal-desktop
        state: present
        update_cache: yes
        become: true
